name: Validate generator
on:
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GIT_CONFIG_COUNT: 1
      GIT_CONFIG_KEY_0: url.https://github.com/.insteadOf
      GIT_CONFIG_VALUE_0: ssh://git@github.com/
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '24.x'
          cache: npm
      - run: npm ci
      - run: npm run coverage
      - run: node test/validation/legacy.js
      - run: npm run build
      - run: npm pack
